
server:
  port: 8080

spring:
  application:
    name: grass-gateway
  cloud:
    gateway:
      default-filters:


eureka:
  instance:
    hostname: 127.0.0.1
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:7000/eureka/

logging:
  level:
    org.springframework.gateway: trace
