
server:
    port: 8082
spring:
  application:
    name: grass-admin
  datasource:
    url: jdbc:mysql://localhost:3306/grass_admin?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: welcome
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver

eureka:
  instance:
    hostname: 127.0.0.1
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:7000/eureka/

# hystrix
feign:
  hystrix:
    enabled: true

# aop
aspect:
  log:
    switcher: true

# set log level
logging:
  level:
    org.grass.admin: debug

# mybatis配置
mybatis:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.grass.**.model
  configuration:
    use-generated-keys: true
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# 分页插件的配置
pagehelper:
  helper-dialect: mysql
  reasonable: true
  page-size-zero: true
